name: Deploy to Hetzner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.20'

      - name: Install dependencies
        run: npm install
        working-directory: './client/'  # Укажи путь к проекту, если нужен
  
      - name: Build project
        run: npm run build
        working-directory: ./client

      - name: Run deployment commands on server
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd ./youtube-download
            git pull
            ./start_docker.sh
